### ISSUE TITLE
It need a MySQL Server to make a IoT Storage - MySQL 서버 필요

### ISSUE THREAD

**Issue by jongkwang** [jongkwang/IoTLabs#10]
It need a MySQL Server to make the IoT Storage

> The IoT Storage is a sub project of IoT Labs
> And It take the communication with MySQL, ElasticSearch ( it can be altered)

It is assigned to me.

---

개발용으로 사용할 MySQL 서버가 필요합니다.

> IoT Labs 에서 데이터 저장 부분을 IoT Storage 라고 부르고 있습니다.
> IoT Storage 는 MySQL 과 ElasticSearch 를 염두해 두고 있지만, 의견을 받아보고 수정 될 수 있습니다.
- MS Azure 환경에 MySQL 서버를 하나 올려 놓고,
- 서버 정보를 Contributor 들과 공유 하겠습니다.
  - Contributor 에 등록되지 않은 분, 누구든지 요청하시면 서버 정보를 보내드리겠습니다. 제게 요청하세요.

이 이슈는 제가 작업 하겠습니다.

**Comment by harleychoe** [comment]
;)

**Comment by JongsoonHwang** [comment]
IOT의 정보들은 대량이라 비정규식인 mogodb를 사용하는 것은 어떨지요?

**Comment by JongsoonHwang** [comment]
mogoDB를 사용하게 되면 나중에 node.js 사용하여 다양한 웹서비스도 가능 할 것 같습니다.

**Comment by jongkwang** [comment]
@JongsoonHwang 님, 말씀 맞습니다.
- 대량의 Log 성 데이터는 NoSQL 에 저장 할 것이고요.
- 소량의 단발성 데이터는 MySQL 에 저장 할 것입니다.

양쪽 기능 모두 지원해야 합니다.
일단 MySQL 먼저 구축 하려 합니다. ^^

**Comment by jongkwang** [comment]
구축 완료 했습니다.
간편하게 AWS 의 RDS 에 구축 하였습니다.

구축 정보는 Slack 으로 공유 하겠습니다.

> 이런 ID/PW 는 어디에 저장 하는 것이 좋을까요??
