### ISSUE TITLE
add travis-ci to test codes

### ISSUE THREAD

**Issue by darjeeling** [jongkwang/IoTLabs#11]

**Comment by jongkwang** [comment]
Thank you for an issue.
I think so. but I didn't use it.

**Is there anyone who can take care of this issue?**
I hope to find someone in charge of the matter until next week on hackathon.

---

이슈는 언제나 감사드려요!!
필요한 기능인데, 제가 해본적이 없어서요.

**누구 혹시 담당해 주실 분 계실까요?**
다음주 해커톤 때 담당자 찾아보고, 그렇지 않으면 제가 맡아서 하는걸로 ^^;;

P.S.
이번 프로젝트는 최대한 영문을 변행 표시 하려 하고 있습니다.
하지만, 국문으로만 남겨주셔도 감사합니다. 괜히 영문으로 남겨야 한다고 부담 갖지 말아주세요.

**Comment by jongkwang** [comment]
@toori67 
How about the Jenkins with some plugin?
It is easy to handle for me. but I didn't use the Travis-Ci

**Let's talk about this which is better to use. on the Hackathon.**
I hope for easy thing to use

---

@toori67 
젠킨스에 플러그인 꽂아서 사용하는 것은 어떤가요?
Travis-Ci 는 안써봐서 그런데, Jenkins 는 워낙 익숙해서요.

어떤 것이든 사람들(개발자 포함)이 쉽게 사용 할 수 있는 것으로 하면 좋겠어요.
**주말 해커톤에 오시면 다른 분들과 상의해서 정해 보죠.**
(저는 Travis-Ci 좀 살펴 볼께요)

**Comment by toori67** [comment]
Since we add `pmd` and `findbugs`, Jenkins would be perfect.
But do we have any hosted server? 

## 

pmd 나 findbugs 가 들어있어서 jenkins 가 좋을거 같습니다.
그런데 프로젝트에서 사용하는 호스팅받는 서버가 있나요?

**Comment by darjeeling** [comment]
how about apply this blog?  
https://angus.nyc/2015/continuous-integration-for-java-github/

**Comment by toori67** [comment]
@darjeeling Great! XD 
I will apply jacoco and etc, along with travis.

**Comment by toori67** [comment]
#29 머지 될때 close 하면 될거 같습니다 :)

**Comment by toori67** [comment]
fix #12
