### ISSUE TITLE
add test to accept pull requests

### ISSUE THREAD

**Issue by darjeeling** [jongkwang/IoTLabs#12]

**Comment by toori67** [comment]
이 이슈도 @jongkwang 님 과 같이 #11 번 이슈 해결할때 처리하겠습니다.

**Comment by toori67** [comment]
travis 가 이 레포지토리를 못 찾는 문제가 있는데 해당 이슈 해결되면 닫겠습니다 :)

**Comment by jongkwang** [comment]
It is solved.
I fell in love with Travis CI

Thank you @darjeeling and @toori67 .
