### ISSUE TITLE
Basic question to understand project

### ISSUE THREAD

**Issue by mjkim610** [jongkwang/IoTLabs#24]
I am an beginner, but I would like to contribute!

I have the code but I don't understand it. There is too much new functions/modules and it is overwhelming.
I have never heard of MQTT, Jenkins, and I have never used Raspberry Pi.

But I have cloned the repo to my desktop and have opened the project with Gradle.
Can I get some tips on what to do next to understand how the project works?

Thank you very much!

---

반갑습니다!

초보자여서 뭘 해야할 지 모르겠습니다.
MQTT, Jenkins, Raspberry Pi 사용 경험도 없고 코드도 clone은 했지만 이해를 못 하고 있습니다 ㅜㅜ

프로젝트를 이해하려면 앞으로 뭘 해야할까요?

감사합니다!

**Comment by mjkim610** [comment]
Tutorial for Java environment setup: https://gist.github.com/toori67/53ba5de0b7c9e37e42e62b0e5b4773a1

Thank you @toori67!

**Comment by mjkim610** [comment]
I'm trying to run gradle test but I keep getting _BUILD FAILED_.
It says **Task 'test' not found in root project 'IoTLabs'**.

What am I doing wrong? please help!

![image](https://cloud.githubusercontent.com/assets/17107206/18809884/d464c010-82c2-11e6-9eec-02cfa3128e8a.png)

**Comment by toori67** [comment]
@mjkim610 You should run those commands inside Platform/Java folder.

**Comment by toori67** [comment]
Also, you should use `gradlew.bat` Not `gradlew` in window env.

**Comment by mjkim610** [comment]
![image](https://cloud.githubusercontent.com/assets/17107206/18812956/116870de-8321-11e6-8609-0f51a519addd.png)

Build was successful in **Git Bash**, **cmd**, and **Intellij terminal**. But **Intellij terminal** encounters errors in Korean commenting.
I am not sure how each command line interface / shell is different from each other and which one would be the best to use in the current environment. Is it highly recommended that I use cygwin instead? Any tips from Windows users?

Thank you!

**Comment by toori67** [comment]
Woyld you check intellij editor's encoding?  I make those test with  utf-8 encoding.

**Comment by mjkim610** [comment]
It was already in utf8 but I changed to ascii then back to utf8. Now it works and no encoding errors! Thank you! I will be using intellij from now on.

**Comment by jongkwang** [comment]
사실 교육이 초반에 충분해야 하는데
그렇지 못한점 미안하네요.
- 해커톤 끝나고 나서 스터디 그룹을 운영 하도록 하겠습니다.

@mjkim610 님, 이슈 정리 되었으면 Close 부탁드려요.
(다른 질문 있으면, 새로운 이슈로 또 작성해주세요 ^^)
