### ISSUE TITLE
Design and 3D print enclosures

### ISSUE THREAD

**Issue by jinheary** [jongkwang/IoTLabs#25]
제품의 케이스 및 부품을 설계 제작합니다.

**Comment by JongsoonHwang** [comment]
http://www.thingiverse.com/thing:1762606
이것을 이용해서 만들어 보면 어떨까요?
아래 링크도 마음에 들긴 하지만 고칠 요소가 많을 것 같습니다.
http://www.thingiverse.com/thing:1548463

**Comment by jongkwang** [comment]
이 이슈는 일단 Close 하고,
필요시 새로운 이슈에서 처리 하도록 하겠습니다.
