### ISSUE TITLE
Slack 채널 구성

### ISSUE THREAD

**Issue by jongkwang** [jongkwang/IoTLabs#26]
P.S.
이번 해커톤 기간(1주일)에는 영어를 쓰지 않겠습니다.
활발한 활동을 요구하는 기간인데,
아무래도 영어 때문에 다들 주춤하실 수 있습니다.

---
## Slack

어제 미팅에서 전체 커뮤니케이션 메신저가 있으면 좋겠다고들 하셨습니다.
메신저는 카톡과 라인... 그리고 페북 메신저가 최고이지만
Slack 을 사용하도록 하겠습니다.

실제로 개발 프로젝트에서 선호하는 메신저이고
Github 와 연동 기능 때문에 공개SW 개발에서 사랑받는 메신저 입니다.

익숙한 카톡/라인보다
공개SW 개발을 경험한다는 취지에서 Slack 으로 운영 하겠습니다.

> Slack + Github 연동 방법 : https://brunch.co.kr/@nser789/5
## 초대장 못받으신분?

초대장 못받으신분은 제게 메일 주세요. kim@jongkwang.com
- 20명 확정 후 합류하신 한분과
- 우즈베키스탄 학생분 못받으셨을 겁니다

**Comment by solit10** [comment]
확인 및 완료했습니다

**Comment by jkiid** [comment]
초대장을 받지 못했습니다! 확인 부탁드리겠습니다.
stype13@gmail.com

**Comment by jongkwang** [comment]
@jkiid 님 초대 다시 했습니다.
스팸함도 보세요 ^^

**Comment by MaestroXHyun** [comment]
확인 및 완료했습니다.

**Comment by jongkwang** [comment]
이 이슈는 종료 하겠습니다.
