### ISSUE TITLE
오픈소스 관련 자료

### ISSUE THREAD

**Issue by solit10** [jongkwang/IoTLabs#33]
오픈소스 관련 자료 사이트를 알고 싶습니다.

**Comment by toori67** [comment]
음 질문을 조금 더 상세하게 해주실수 있으신가요? 어떤 쪽의 내용을 알고 싶으신가요?

**Comment by solit10** [comment]
오픈소스 관련 사이트가 무척 많은 관계로 github 말고 다른 오픈소스 사이트 중 라이센스와 무관하게 사용할 수 있는 사이트를 추천받고자 글을 쓰게 되었습니다.

**Comment by jongkwang** [comment]
Github에 보이는 거의 모든 프로젝트는 공개SW 입니다.
- Github은 공개SW에 대해 Github을 무료로 제공하고 있습니다.
- Private 로 운영하고 싶으시면 Github의 유료 서비스를 받으셔야 합니다.
- 전체가 아니고 거의 모든 프로젝트인 이유는
  - 몇몇 아닌것도 있고(여태 보지 못했음)
  - 공개SW 이기는 한데 License 가 너무 엄격한 경우가 있을 수 있습니다. (하지만 거의 없음)

Github 가 세계 최대 공개SW 공간 입니다.
다른 곳에서 찾으실 필요가 없습니다. ^^

#### Github 에서 가장 인기있는 프로젝트 찾기
- 깃헙에서 가장 활발한 프로젝트 : https://github.com/trending
  - 현재 1위는 텐센트의 <code>tinker</code> 라는 프로젝트군요

이 페이지를 보시면,
어느회사의 어떤 프로젝트가 인기 있는지 알 수 있습니다.

> 답변 되셨으면 이슈를 Close 해주세요 ^^
