### ISSUE TITLE
번역팀

### ISSUE THREAD

**Issue by mjkim610** [jongkwang/IoTLabs#34]
번역팀에서 기여가 가능할 것 같습니다. 같이 번역/영어 작업 하실 분 댓글 남겨주시면 감사하겠습니다!

**Comment by mjkim610** [comment]
README 1차 번역 마쳤습니다. 영어가 어색한 부분이 반드시 있을테니 알려주시면 반영하겠습니다.

또 Wiki에 있는 사례 정리도 번역을 해야할지 궁금합니다.

**Comment by jongkwang** [comment]
README.md 봤습니다.
너무 멋져요 👍 

일단 Wiki 및 다른 번역이 급한것은 없습니다. ^^;;

너무빨리 일을 끝내주셔서
어떤것을 드려야 할지 난감 하네요 ^^;;

**Comment by jongkwang** [comment]
완료 처리 합니다.^^
수고 많으셨습니다.!!
