### ISSUE TITLE
H/W와 S/W관련

### ISSUE THREAD

**Issue by solit10** [jongkwang/IoTLabs#35]
H/W에 arduino를 쓰실건지 Raspberry Pi를 쓰실껀지
S/W 관련해서는 언어를 어떤 것을 쓸 것인지 기준을 명확하게 정해 주셨으면 좋겠습니다.

**Comment by jwsong94** [comment]
제가 그때 이야기 나눴을 때에는 황종순씨가 화분 쪽에서 Arduino를 사용하신다고 하셨습니다. 아마 지진알림이와  LED Tutorial에서는 Raspberry Pi를 사용하지 않을까 싶습니다.

**Comment by jkiid** [comment]
가장 기본이 되는 LED Tutorial의 경우 두가지 HW 모두를 사용해 보아도 괜찮지 않을까 합니다.

**Comment by jwsong94** [comment]
그러면 LED Tutorial은 Arduino와 Raspberry Pi 모두 만드는 방향으로 하겠습니다.

**Comment by jongkwang** [comment]
궁극적으로는 2개 Device 모두 필요합니다.
(2개 뿐 아니라 범용적인 모든 디바이스 필요)

하지만, 시간적 제약이 있으니까.
담당자 편한것 부터 만드는 것이 좋겠습니다. ^^

이 이슈는 종료된 것 같으니 Close 하겠습니다.
