### ISSUE TITLE
Mqtt table한번 만들어봤습니다..

### ISSUE THREAD

**Issue by ShInJaYong** [jongkwang/IoTLabs#44]
![mqtt_schema](https://cloud.githubusercontent.com/assets/20179919/18839278/5ddf0156-8445-11e6-8a54-44731ffdb914.png)
위도와 경도는 double type로 넣었고,
나머지는 머신 정보들 입니다.

**Comment by toori67** [comment]
정규화를 해서 Sensor-Data 를 `1 to many` 로 쪼개고 Data 의 f-key 는 Sensor#id 를 가지면 어떨까요?

![1ton](https://cloud.githubusercontent.com/assets/1668881/18842381/bec21e18-844f-11e6-9ccd-f64ca8f4c903.png)

**Comment by jkiid** [comment]
f-key는 무엇을 말하는건가요? Data의 행중 하나로 Sensor#가 들어가도록 하면 되는것 인가요?

**Comment by toori67** [comment]
sendor table 을 만들고 해당 테이블의 pkey 로 sensor_id 가 들어가고, 그 id 를 외래키로 바라보고 있는 data 테이블을 만드는게 어떤가 라는 질문이였습니다! :) @jkiid

**Comment by ShInJaYong** [comment]
@toori67  아.. 깃확인을 이제 했네요... 근데 간단한 디비 구조인데 쪼개면 퍼포먼스가 떨어지지 않을까요..? 나중에 데이터가 동시에 많이 날아올텐데 join문 쓰게되면 퍼포먼스가 떨어질까봐요..

**Comment by toori67** [comment]
@ShInJaYong 실제로 `insert` 는 `Data` 테이블 쪽에서 발생하지 않을까요?? `sendor_id` 는 어차피 index 가 걸릴꺼라서 Data 테이블 검색에는 큰 무리가 없을거 같아 보이는데...
제가 잘 몰라서..ㅠㅠ

**Comment by jongkwang** [comment]
요즘 `원격 근무의 어려움`에 대해 느끼고 있습니다.
미국에서는 많이들 한다고 하는데 어떻게 가능한지 모르겠네요.

일단 대략 정리하고,
나중에 미팅을 통해 다시 구성해야 겠습니다.
확실히 원격근무는 어렵네요 ^^;;

**Comment by jongkwang** [comment]
이 이슈는 일단 Close 하고,
필요시 새로운 이슈에서 처리 하도록 하겠습니다.
