### ISSUE TITLE
화분 전자 부품 목록

### ISSUE THREAD

**Issue by JongsoonHwang** [jongkwang/IoTLabs#59]
WIKI에 쓰는 권한이 없어서 여기에 올립니다.
(급하게 찾아서 몇가지는 테스트 및 연구가 필요한 부품이 있습니다.)
1. 빵판과 아두이노 우노 : http://www.devicemart.co.kr/1265051 : 32000
2. 수분감지센서 : http://www.devicemart.co.kr/1272998
3. 점퍼와이어 m/m : http://www.devicemart.co.kr/1272911 : 23000
4. 점퍼와이어 f/m : http://www.devicemart.co.kr/1272907 : 29400
5. 점퍼와이어 키트 : http://www.devicemart.co.kr/1311173 : 3900
6. 만능기판  : http://www.devicemart.co.kr/31241 : 3300 2개 6600
7. 전원부 : GeDuino Battery Shield: http://www.devicemart.co.kr/1077254 : 18000
8. DHT11 온습도 센서모듈 [SZH-EK024] : http://www.devicemart.co.kr/1278926 3300
9. wifi 모듈 2개(각기 다른 종류 모두 필요) : http://www.devicemart.co.kr/1149104
                                   http://www.devicemart.co.kr/1272393 
10. mpu6050 : MPU-6050 6축 자이로 가속도 센서 모듈 GY-521 [SZH-EK007] : http://www.devicemart.co.kr/1247052 : 2700
11. AA 건전지 : 8개
12. 릴레이 2개 : http://www.devicemart.co.kr/1149070와 http://www.devicemart.co.kr/1160419
13. 전원 공급기 : http://www.devicemart.co.kr/1236946

**Comment by jongkwang** [comment]
> Wiki 편집 권한이 없는 것을 확인 못했습니다. ^^;;

작성해주신 부품목록을 장바구니에 담아 봤습니다.
예산적인 문제가 있어서 Slack #project-pot 채널에 메시지 남겨 놨습니다.

**Comment by jongkwang** [comment]
H/W 지원이 원활하지 못해 죄송하네요.
이 이슈는 Close 하겠습니다.
