### ISSUE TITLE
README.md 페이지 영문 번역본 적용하기

### ISSUE THREAD

**Issue by jongkwang** [jongkwang/IoTLabs#61]
@mjkim610 님,
## 작업요청
- https://github.com/jongkwang/IoTLabs/blob/master/Documents/90_Communication/English%20Translate/README_ENG.md 이 내용을
- https://github.com/jongkwang/IoTLabs/blob/master/README.md 여기에 Merge 해주세요.
## 순서
- 순서1 : 한글 Dashboard 가 먼저 나오고
- 순서2 : 영문 README 내용이 나오고
- 순서3 : 한글 README 내용이 나왔으면 좋겠습니다.
- 그리고, 이 이슈 Close 해주세요

감사합니다.^^

**Comment by mjkim610** [comment]
1차 적용 pr했습니다. 리뷰 해주신 후 문제 없을시 close하겠습니다!

**Comment by mjkim610** [comment]
제가 open 한 이슈가 아니라서 close 권한이 없는 것 같습니다!

**Comment by jongkwang** [comment]
앗... 그렇군요.
저도 권한 관련해서 익숙하지 않아서.

등록하신 것 잘 봤어요!!
