### ISSUE TITLE
It need a MQTT Broker for test and development. - MQTT 브로커 필요

### ISSUE THREAD

**Issue by jongkwang** [jongkwang/IoTLabs#9]
**It need a MQTT Broker for development environment**
- It is assigned to me. I will do it.

---

**개발환경을 위해 MQTT Broker 가 필요합니다.**
- 이슈 메뉴 활성화를 위해, 작업하기 전 이슈 생성을 먼저 하고 있습니다.
- 이 작업은 제가 처리 하도록 하겠습니다. (AWS 에 생성하려 합니다)
- 가급적 영어로 작성하고 싶지만 쉽지 않네요 ^^;;

**Comment by toori67** [comment]
Simple mqtt broker already exist in project.

`gradlew -q start_mqtt_broker` will start broker in local. 

---

이미 moquette 를 이용해서 테스트 용도 브로커를 띄울수가 있습니다. 다른 브로커를 구현하려고 하시는 건가요? :)

**Comment by jongkwang** [comment]
Oh.. You're right
I just slipped your commit 😃 

I thought it is a hard task to build a MQTT Broker.
But, you had a simple method. (I have been try it with the Rabbit MQ. And it was hard work 😭 )

Now, I'll try it with Moquette.
It looks good 😃 

---

커밋 하신것 제가 머지 했는데,
깜빡 했어요 ^^;;
(알려줘서 고마워요.)

누구나 쉽게 MQTT Broker 를 이용 할 수 있도록,
공용으로 사용할 서버를 Rabbit MQ 로 띄웠었어요.

그런데 이렇게 쉽게 Moquette 를 띄울 수 있다면,
그냥 Moquette 로 Local 에 돌려도 되겠네요 ^^
