### ISSUE TITLE
Xiaomi YeeLight를 컨트롤하는 프로젝트가 필요합니다. 

### ISSUE THREAD

**Issue by larvinion** [jongkwang/IoTLabs#98]
Xiaomi YeeLight 를 컨트롤하는 작업이 필요합니다.

**Comment by BlackJIN** [comment]
OS : Linux기반(CentOS 로 테스트 했습니다.)

YeeLightBlue.java 안에 connect / trunOff / turnOn / intcontrol(RGB 색깔 조절 & 밝기 조절) 메소드 있습니다. connect 메소드 부분에서 소스 안에서 블루투스 Device number 와 제어할 YeeLight MaxAddress를 직접 입력해야 합니다. 이 부분을 차후 수정이 필요합니다.
